title: "امیرعلی سطوتی"
description: "پورتفولیوی علوم داده"
url: "https://amiralisatvati.github.io"
baseurl: ""

# تم
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

# پلاگین‌ها
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# تنظیمات پایه
locale: "fa-IR"
search: true

# نویسنده
author:
  name: "امیرعلی سطوتی"
  bio: "دانشجوی علوم داده"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amiralisatvati"

# پیش‌فرض‌ها
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
