# ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ù¾ÙˆØ±ØªÙÙˆÙ„ÛŒÙˆÛŒ Ø§Ù…ÛŒØ±Ø¹Ù„ÛŒ Ø³Ø·ÙˆØªÛŒ
title: "Ù¾ÙˆØ±ØªÙÙˆÙ„ÛŒÙˆÛŒ Ø§Ù…ÛŒØ±Ø¹Ù„ÛŒ Ø³Ø·ÙˆØªÛŒ"
name: "Ø§Ù…ÛŒØ±Ø¹Ù„ÛŒ Ø³Ø·ÙˆØªÛŒ"
description: "Ø¯Ø§Ù†Ø´Ø¬ÙˆÛŒ Ø¹Ù„ÙˆÙ… Ø¯Ø§Ø¯Ù‡ | ØªØ­Ù„ÛŒÙ„ Ø¢Ù…Ø§Ø±ÛŒ | Ù¾Ø§ÛŒØªÙˆÙ† Ùˆ R"

# --- ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ù…Ù‡Ù… Ø²Ø¨Ø§Ù† (Ø±Ø§Ø³Øªâ€ŒÚ†ÛŒÙ†) ---
locale: "fa-IR"
direction: "rtl"
url: "https://amiralisatvati.github.io"

# --- Ù‚Ø§Ù„Ø¨ Ùˆ Ø¸Ø§Ù‡Ø± ---
minimal_mistakes_skin: "default" # Ù¾ÙˆØ³ØªÙ‡â€ŒÙ‡Ø§ÛŒ Ø¯ÛŒÚ¯Ø±: air, sunrise, aqua
search: true

# --- ØªÙ†Ø¸ÛŒÙ…Ø§Øª ÙÙ†ÛŒ ---
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# --- Ù…Ø´Ø®ØµØ§Øª Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ (Ø³Ø§ÛŒØ¯Ø¨Ø§Ø±) ---
author:
  name        : "Ø§Ù…ÛŒØ±Ø¹Ù„ÛŒ Ø³Ø·ÙˆØªÛŒ"
  bio         : "ğŸ‘¨â€ğŸ’» Ø¯Ø§Ù†Ø´Ø¬ÙˆÛŒ Ø¹Ù„ÙˆÙ… Ø¯Ø§Ø¯Ù‡ <br> ğŸ“Š ØªØ­Ù„ÛŒÙ„ Ø¢Ù…Ø§Ø±ÛŒ"
  location    : "Iran"
  links:
    - label: "Ú¯ÛŒØªâ€ŒÙ‡Ø§Ø¨"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amiralisatvati"
    - label: "Ù„ÛŒÙ†Ú©Ø¯ÛŒÙ†"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/amirali-satvati"
    - label: "ØªÙ„Ú¯Ø±Ø§Ù…"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/amirali_satvati"

# --- ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ù¾Ø³Øªâ€ŒÙ‡Ø§ ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true